import { Response } from 'express';
import { AuthRequest } from '../middlewares/auth';
import { isFieldOfficer } from '../auth/roles';
import prisma from '../config/database';
import archiver from 'archiver';
import ExcelJS from 'exceljs';
import { tallyStatusCounts } from '../utils/reportStatus';
import fs from 'fs';
import path from 'path';
import { env } from '../config/env';
import { Request } from "express";
import { errorResponse, notFoundResponse } from '../utils/response';

const UPLOAD_BASE_DIR = path.join(process.cwd(), env.UPLOAD_DIR);
const TEMP_DIR = path.join(process.cwd(), 'temp');

// Ensure temp directory exists
if (!fs.existsSync(TEMP_DIR)) {
  fs.mkdirSync(TEMP_DIR, { recursive: true });
}

// Clean up temp file
const cleanupTempFile = (filePath: string) => {
  setTimeout(() => {
    if (fs.existsSync(filePath)) {
      fs.unlinkSync(filePath);
    }
  }, 60000); // Delete after 1 minute
};

// Generate text summary for laporan
const generateLaporanSummary = (laporan: any, jenis: string): string => {
  let content = '';
  
  if (jenis === 'awal') {
    content = `
LAPORAN AWAL PEKERJAAN
═══════════════════════════════════════════════════════

ID Laporan      : ${laporan.reportId}
Tanggal         : ${laporan.tanggal}
Hari            : ${laporan.hari}
Nomor SPJ       : ${laporan.nomorSPJ}
UP3             : ${laporan.up3}

INFORMASI PEKERJAAN
────────────────────────────────────────────────────────
Pekerjaan       : ${laporan.pekerjaan}
Lokasi Gardu    : ${laporan.lokasiGardu}

TIM PELAKSANA
────────────────────────────────────────────────────────
Pelaksana           : ${laporan.pelaksana}
Penanggung Jawab    : ${laporan.penanggungJawab}
Pengawas Pekerjaan  : ${laporan.pengawasPekerjaan || '-'}
Pengawas Manuver    : ${laporan.pengawasManuver || '-'}
Pengawas K3         : ${laporan.pengawasK3 || '-'}
Nomor WP            : ${laporan.nomorWP || '-'}

PERSONIL BERTUGAS (${laporan.jumlahPersonil ?? (Array.isArray(laporan.personilSnapshot) ? laporan.personilSnapshot.length : 0)} orang)
────────────────────────────────────────────────────────
${Array.isArray(laporan.personilSnapshot) && laporan.personilSnapshot.length > 0
  ? laporan.personilSnapshot.map((p: any, i: number) => `${i + 1}. ${p.nama}${p.jabatan ? ` (${p.jabatan})` : ''}`).join('\n')
  : '-'}

SAFETY CHECKLIST (K3)
────────────────────────────────────────────────────────
WP/JSA/HIRARC/SOP         : ${laporan.wpJsahirarcSop ? 'Ya' : 'Tidak'}
Kondisi Personil          : ${laporan.kondisiPersonil || '-'}
Potensi Bahaya Dijelaskan : ${laporan.potensiBahayaDijelaskan ? 'Ya' : 'Tidak'}
APD Lengkap               : ${laporan.apdLengkap ? 'Ya' : 'Tidak'}
Asuransi Ketenagakerjaan  : ${laporan.asuransiKetenagakerjaan ? 'Ya' : 'Tidak'}
Berdoa Sebelum Bekerja    : ${laporan.berdoaSebelumBekerja ? 'Ya' : 'Tidak'}

KESELAMATAN KERJA
────────────────────────────────────────────────────────
Potensi Bahaya      :
${laporan.potensiBahaya}

Pengendalian Risiko :
${laporan.pengendalianRisiko}

APD                 : ${laporan.apd || '-'}
Rambu Kerja         : ${laporan.rambuKerja || '-'}
Asuransi TK         : ${laporan.asuransiTK || '-'}

STATUS
────────────────────────────────────────────────────────
Status              : ${laporan.status}
Dibuat oleh         : ${laporan.createdBy?.name || '-'}
Tanggal dibuat      : ${laporan.createdAt}

═══════════════════════════════════════════════════════
Generated by VoltHub System
${new Date().toISOString()}
`;
  } else if (jenis === 'akhir') {
    content = `
LAPORAN AKHIR PEKERJAAN
═══════════════════════════════════════════════════════

ID Laporan      : ${laporan.reportId}
Tanggal Selesai : ${laporan.tanggalSelesai}
Nomor SPJ       : ${laporan.nomorSPJ}
UP3             : ${laporan.up3}

ASSET & LOKASI
────────────────────────────────────────────────────────
Nama Aset       : ${laporan.namaAset}
Tag SCADA       : ${laporan.tagSCADA || '-'}
Bay Posisi      : ${laporan.bayPosisi || '-'}
Tegangan Nominal: ${laporan.teganganNominal || '-'}

PEKERJAAN
────────────────────────────────────────────────────────
Pekerjaan       : ${laporan.pekerjaan}
Detail Langkah  :
${laporan.detailLangkah}

HASIL
────────────────────────────────────────────────────────
Status Pekerjaan        : ${laporan.statusPekerjaan}
Tahanan Isolasi         : ${laporan.hasilTahananIsolasi || '-'}
Hasil Pengukuran Beban  : ${laporan.hasilPengukuranBeban || '-'}
Catatan Hasil           : ${laporan.catatanHasil || '-'}
Durasi Pekerjaan        : ${laporan.durasiPekerjaan || '-'}
Catatan Tambahan        : ${laporan.catatanTambahan || '-'}

STATUS
────────────────────────────────────────────────────────
Status          : ${laporan.status}
Dibuat oleh     : ${laporan.createdBy?.name || '-'}
Tanggal dibuat  : ${laporan.createdAt}

═══════════════════════════════════════════════════════
Generated by VoltHub System
${new Date().toISOString()}
`;
  }

  return content;
};

// Export single laporan as ZIP
export const exportZip = async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    const { jenis, id } = req.params;
    const userId = req.user?.userId;
    const userRole = req.user?.role;

    if (!userId || !userRole) {
      errorResponse(res, 'User not authenticated', 401);
      return;
    }

    // Validate jenis
    const validJenis = ['awal', 'akhir'];
    if (!validJenis.includes(jenis)) {
      errorResponse(res, 'Invalid jenis. Use: awal, akhir', 400);
      return;
    }

    // Fetch laporan with attachments
    let laporan: any;

    if (jenis === 'awal') {
      laporan = await prisma.laporanAwal.findUnique({
        where: { id },
        include: {
          attachments: true,
          createdBy: { select: { name: true, email: true } },
        },
      });
    } else {
      laporan = await prisma.laporanAkhir.findUnique({
        where: { id },
        include: {
          attachments: true,
          createdBy: { select: { name: true, email: true } },
        },
      });
    }

    if (!laporan) {
      notFoundResponse(res, 'Laporan not found');
      return;
    }

    // Check access — only field officers (PETUGAS) are limited to their own
    // reports; MASTER/MANAGER/ADMIN may export any.
    if (isFieldOfficer(userRole) && laporan.createdById !== userId) {
      errorResponse(res, 'Access denied', 403);
      return;
    }

    // Create temp ZIP file
    const zipFileName = `${laporan.reportId}.zip`;
    const zipFilePath = path.join(TEMP_DIR, zipFileName);

    // Create archiver
    const archive = archiver('zip', { zlib: { level: 9 } });
    const output = fs.createWriteStream(zipFilePath);

    // Set response headers
    res.setHeader('Content-Type', 'application/zip');
    res.setHeader('Content-Disposition', `attachment; filename="${zipFileName}"`);

    // Pipe archive to response
    archive.pipe(output);
    archive.pipe(res);

    // Add text summary
    const summary = generateLaporanSummary(laporan, jenis);
    archive.append(summary, { name: `laporan_${jenis}.txt` });

    // Add attachments
    for (const attachment of laporan.attachments) {
      if (fs.existsSync(attachment.path)) {
        const folderName = attachment.category.toLowerCase().replace(/_/g, '-');
        archive.file(attachment.path, { name: `${folderName}/${attachment.originalName}` });
      } else {
        console.warn(`File not found on disk: ${attachment.path}`);
      }
    }

    // Finalize
    await archive.finalize();

    // Log activity
    await prisma.activityLog.create({
      data: {
        userId,
        action: 'DOWNLOAD',
        entityType: jenis === 'awal' ? 'LAPORAN_AWAL' : 'LAPORAN_AKHIR',
        entityId: id,
        details: JSON.stringify({
          exportType: 'ZIP',
          reportId: laporan.reportId,
        }),
      },
    });

    // Cleanup temp file after streaming
    output.on('close', () => {
      cleanupTempFile(zipFilePath);
    });

  } catch (error) {
    console.error('Export ZIP error:', error);
    errorResponse(res, 'Failed to export ZIP', 500);
  }
};

// Export history as XLSX
export const exportXlsx = async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    const userId = req.user?.userId;
    const userRole = req.user?.role;

    if (!userId || !userRole) {
      errorResponse(res, 'User not authenticated', 401);
      return;
    }

    const { jenis, status, startDate, endDate, rtupp, team } = req.query;

    // Build base where — only PETUGAS is restricted to their own reports.
    const baseWhere: Record<string, unknown> = {};
    if (isFieldOfficer(userRole)) {
      baseWhere.createdById = userId;
    }
    if (status) baseWhere.status = status;
    
    // Date range
    if (startDate || endDate) {
      (baseWhere as Record<string, Record<string, Date>>).createdAt = {};
      if (startDate) (baseWhere as Record<string, Record<string, Date>>).createdAt.gte = new Date(startDate as string);
      if (endDate) (baseWhere as Record<string, Record<string, Date>>).createdAt.lte = new Date(endDate as string + 'T23:59:59');
    }

    // Create workbook
    const workbook = new ExcelJS.Workbook();
    workbook.creator = 'VoltHub';
    workbook.created = new Date();

    // Determine which sheets to create
    const jenisFilter = jenis as string;
    const createAwal = !jenisFilter || jenisFilter === 'ALL' || jenisFilter === 'AWAL';
    const createAkhir = !jenisFilter || jenisFilter === 'ALL' || jenisFilter === 'AKHIR';

    // Laporan Awal Sheet
    if (createAwal) {
      const awalWhere = { ...baseWhere };
      if (rtupp) awalWhere.up3 = rtupp;

      const awalData = await prisma.laporanAwal.findMany({
        where: awalWhere,
        include: {
          createdBy: {
            select: { name: true, rtupp: true, team: true },
          },
        },
        orderBy: { createdAt: 'desc' },
      });

      const sheet = workbook.addWorksheet('Laporan Awal');
      
      // Header styling
      const headerRow = sheet.addRow([
        'Tanggal', 'Jenis', 'Report ID', 'Petugas', 'RTUPP', 'Team',
        'Status', 'Nomor SPJ', 'Lokasi Gardu', 'Pekerjaan'
      ]);
      headerRow.font = { bold: true, color: { argb: 'FFFFFFFF' } };
      headerRow.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF0066CC' } };
      
      // Add data
      awalData.forEach(item => {
        sheet.addRow([
          item.tanggal.toISOString().split('T')[0],
          'Laporan Awal',
          item.reportId,
          item.createdBy?.name || '-',
          item.createdBy?.rtupp?.name || item.up3,
          item.createdBy?.team?.name || '-',
          item.status,
          item.nomorSPJ,
          item.lokasiGardu,
          item.pekerjaan,
        ]);
      });

      // Auto width
      sheet.columns.forEach(column => {
        column.width = 20;
      });
    }

    // Laporan Akhir Sheet
    if (createAkhir) {
      const akhirWhere = { ...baseWhere };
      if (rtupp) akhirWhere.up3 = rtupp;

      const akhirData = await prisma.laporanAkhir.findMany({
        where: akhirWhere,
        include: {
          createdBy: {
            select: { name: true, rtupp: true, team: true },
          },
        },
        orderBy: { createdAt: 'desc' },
      });

      const sheet = workbook.addWorksheet('Laporan Akhir');
      
      const headerRow = sheet.addRow([
        'Tanggal Selesai', 'Jenis', 'Report ID', 'Petugas', 'RTUPP', 'Team',
        'Status', 'Nomor SPJ', 'Nama Aset', 'Pekerjaan', 'Status Pekerjaan'
      ]);
      headerRow.font = { bold: true, color: { argb: 'FFFFFFFF' } };
      headerRow.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF0066CC' } };
      
      akhirData.forEach(item => {
        sheet.addRow([
          item.tanggalSelesai.toISOString().split('T')[0],
          'Laporan Akhir',
          item.reportId,
          item.createdBy?.name || '-',
          item.createdBy?.rtupp?.name || item.up3,
          item.createdBy?.team?.name || '-',
          item.status,
          item.nomorSPJ,
          item.namaAset,
          item.pekerjaan,
          item.statusPekerjaan,
        ]);
      });

      sheet.columns.forEach(column => {
        column.width = 20;
      });
    }

    // Summary Sheet (if ALL)
    if (!jenisFilter || jenisFilter === 'ALL') {
      const summarySheet = workbook.addWorksheet('Summary');
      
      const headerRow = summarySheet.addRow(['Jenis Laporan', 'Total', 'DRAFT', 'PENDING', 'APPROVED', 'REJECTED', 'REVISED']);
      headerRow.font = { bold: true, color: { argb: 'FFFFFFFF' } };
      headerRow.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF0066CC' } };

      // Get counts
      const [awalCounts, akhirCounts] = await Promise.all([
        prisma.laporanAwal.groupBy({
          by: ['status'],
          where: isFieldOfficer(userRole) ? { createdById: userId } : {},
          _count: { status: true },
        }),
        prisma.laporanAkhir.groupBy({
          by: ['status'],
          where: isFieldOfficer(userRole) ? { createdById: userId } : {},
          _count: { status: true },
        }),
      ]);

      const awalStats = tallyStatusCounts(awalCounts);
      const akhirStats = tallyStatusCounts(akhirCounts);

      summarySheet.addRow(['Laporan Awal', awalStats.total, awalStats.DRAFT, awalStats.PENDING, awalStats.APPROVED, awalStats.REJECTED, awalStats.REVISED]);
      summarySheet.addRow(['Laporan Akhir', akhirStats.total, akhirStats.DRAFT, akhirStats.PENDING, akhirStats.APPROVED, akhirStats.REJECTED, akhirStats.REVISED]);
      summarySheet.addRow(['TOTAL', awalStats.total + akhirStats.total, '', '', '', '', '']);

      summarySheet.columns.forEach(column => {
        column.width = 15;
      });
    }

    // Generate filename
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
    const fileName = `VoltHub_History_${timestamp}.xlsx`;

    // Set headers
    res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    res.setHeader('Content-Disposition', `attachment; filename="${fileName}"`);

    // Write to response
    await workbook.xlsx.write(res);
    res.end();

    // Log activity
    await prisma.activityLog.create({
      data: {
        userId,
        action: 'EXPORT',
        entityType: 'LAPORAN_AWAL', // Using as general export marker
        details: JSON.stringify({
          exportType: 'XLSX',
          jenis: jenis || 'ALL',
          filters: { status, startDate, endDate, rtupp, team }
        }),
      },
    });

  } catch (error) {
    console.error('Export XLSX error:', error);
    errorResponse(res, 'Failed to export XLSX', 500);
  }
};
