/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as V2RouteImport } from './routes/v2'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as R404RouteImport } from './routes/404'
import { Route as IndexRouteImport } from './routes/index'
import { Route as V2IndexRouteImport } from './routes/v2.index'
import { Route as VerifyIdRouteImport } from './routes/verify.$id'
import { Route as V2SplatRouteImport } from './routes/v2.$'
import { Route as AppWorkOrderRouteImport } from './routes/_app.work-order'
import { Route as AppWallRouteImport } from './routes/_app.wall'
import { Route as AppValidasiRouteImport } from './routes/_app.validasi'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppTicketsRouteImport } from './routes/_app.tickets'
import { Route as AppTeamsRouteImport } from './routes/_app.teams'
import { Route as AppTeamRouteImport } from './routes/_app.team'
import { Route as AppSyncRouteImport } from './routes/_app.sync'
import { Route as AppScadaUploadRouteImport } from './routes/_app.scada-upload'
import { Route as AppScadaRealtimeRouteImport } from './routes/_app.scada-realtime'
import { Route as AppScadaLinesRouteImport } from './routes/_app.scada-lines'
import { Route as AppScadaRouteImport } from './routes/_app.scada'
import { Route as AppRtuppRouteImport } from './routes/_app.rtupp'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppRekapAkhirRouteImport } from './routes/_app.rekap-akhir'
import { Route as AppRekapRouteImport } from './routes/_app.rekap'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppPersonilRouteImport } from './routes/_app.personil'
import { Route as AppPerformanceRouteImport } from './routes/_app.performance'
import { Route as AppPenyulangRouteImport } from './routes/_app.penyulang'
import { Route as AppMonitoringRouteImport } from './routes/_app.monitoring'
import { Route as AppLaporanMonitoringRouteImport } from './routes/_app.laporan-monitoring'
import { Route as AppLaporanAwalRouteImport } from './routes/_app.laporan-awal'
import { Route as AppLaporanAkhirRouteImport } from './routes/_app.laporan-akhir'
import { Route as AppLapanganRouteImport } from './routes/_app.lapangan'
import { Route as AppKpiRouteImport } from './routes/_app.kpi'
import { Route as AppInspeksiMpRouteImport } from './routes/_app.inspeksi-mp'
import { Route as AppInspeksiGiRouteImport } from './routes/_app.inspeksi-gi'
import { Route as AppInspeksiGhRouteImport } from './routes/_app.inspeksi-gh'
import { Route as AppInspectionRouteImport } from './routes/_app.inspection'
import { Route as AppImportsRouteImport } from './routes/_app.imports'
import { Route as AppHistoryRouteImport } from './routes/_app.history'
import { Route as AppHarMpRouteImport } from './routes/_app.har-mp'
import { Route as AppHarGiRouteImport } from './routes/_app.har-gi'
import { Route as AppHarGhRouteImport } from './routes/_app.har-gh'
import { Route as AppHarRouteImport } from './routes/_app.har'
import { Route as AppGisRouteImport } from './routes/_app.gis'
import { Route as AppGiDashboardRouteImport } from './routes/_app.gi-dashboard'
import { Route as AppGarduRouteImport } from './routes/_app.gardu'
import { Route as AppExportRouteImport } from './routes/_app.export'
import { Route as AppDocumentsRouteImport } from './routes/_app.documents'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCommunicationMediaRouteImport } from './routes/_app.communication-media'
import { Route as AppBayRouteImport } from './routes/_app.bay'
import { Route as AppAssetRouteImport } from './routes/_app.asset'
import { Route as AppAiSearchRouteImport } from './routes/_app.ai-search'
import { Route as AppWorkOrderIdRouteImport } from './routes/_app.work-order.$id'
import { Route as AppTicketsIdRouteImport } from './routes/_app.tickets.$id'
import { Route as AppPerformanceIdRouteImport } from './routes/_app.performance.$id'
import { Route as AppPenyulangIdRouteImport } from './routes/_app.penyulang.$id'
import { Route as AppLaporanCreateRouteImport } from './routes/_app.laporan.create'
import { Route as AppLaporanAwalIdRouteImport } from './routes/_app.laporan-awal.$id'
import { Route as AppLaporanAkhirIdRouteImport } from './routes/_app.laporan-akhir.$id'
import { Route as AppInspeksiMpIdRouteImport } from './routes/_app.inspeksi-mp.$id'
import { Route as AppInspeksiGiIdRouteImport } from './routes/_app.inspeksi-gi.$id'
import { Route as AppInspeksiGhIdRouteImport } from './routes/_app.inspeksi-gh.$id'
import { Route as AppInspectionIdRouteImport } from './routes/_app.inspection.$id'
import { Route as AppImportsIdRouteImport } from './routes/_app.imports.$id'
import { Route as AppHarIdRouteImport } from './routes/_app.har.$id'
import { Route as AppHarMpIdRouteImport } from './routes/_app.har-mp.$id'
import { Route as AppHarGiIdRouteImport } from './routes/_app.har-gi.$id'
import { Route as AppHarGhIdRouteImport } from './routes/_app.har-gh.$id'
import { Route as AppGarduIdRouteImport } from './routes/_app.gardu.$id'
import { Route as AppDocumentsIdRouteImport } from './routes/_app.documents.$id'
import { Route as AppCommunicationMediaIdRouteImport } from './routes/_app.communication-media.$id'
import { Route as AppAssetIdRouteImport } from './routes/_app.asset.$id'

const V2Route = V2RouteImport.update({
  id: '/v2',
  path: '/v2',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const V2IndexRoute = V2IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => V2Route,
} as any)
const VerifyIdRoute = VerifyIdRouteImport.update({
  id: '/verify/$id',
  path: '/verify/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const V2SplatRoute = V2SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => V2Route,
} as any)
const AppWorkOrderRoute = AppWorkOrderRouteImport.update({
  id: '/work-order',
  path: '/work-order',
  getParentRoute: () => AppRoute,
} as any)
const AppWallRoute = AppWallRouteImport.update({
  id: '/wall',
  path: '/wall',
  getParentRoute: () => AppRoute,
} as any)
const AppValidasiRoute = AppValidasiRouteImport.update({
  id: '/validasi',
  path: '/validasi',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTicketsRoute = AppTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamsRoute = AppTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppSyncRoute = AppSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => AppRoute,
} as any)
const AppScadaUploadRoute = AppScadaUploadRouteImport.update({
  id: '/scada-upload',
  path: '/scada-upload',
  getParentRoute: () => AppRoute,
} as any)
const AppScadaRealtimeRoute = AppScadaRealtimeRouteImport.update({
  id: '/scada-realtime',
  path: '/scada-realtime',
  getParentRoute: () => AppRoute,
} as any)
const AppScadaLinesRoute = AppScadaLinesRouteImport.update({
  id: '/scada-lines',
  path: '/scada-lines',
  getParentRoute: () => AppRoute,
} as any)
const AppScadaRoute = AppScadaRouteImport.update({
  id: '/scada',
  path: '/scada',
  getParentRoute: () => AppRoute,
} as any)
const AppRtuppRoute = AppRtuppRouteImport.update({
  id: '/rtupp',
  path: '/rtupp',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRekapAkhirRoute = AppRekapAkhirRouteImport.update({
  id: '/rekap-akhir',
  path: '/rekap-akhir',
  getParentRoute: () => AppRoute,
} as any)
const AppRekapRoute = AppRekapRouteImport.update({
  id: '/rekap',
  path: '/rekap',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPersonilRoute = AppPersonilRouteImport.update({
  id: '/personil',
  path: '/personil',
  getParentRoute: () => AppRoute,
} as any)
const AppPerformanceRoute = AppPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AppRoute,
} as any)
const AppPenyulangRoute = AppPenyulangRouteImport.update({
  id: '/penyulang',
  path: '/penyulang',
  getParentRoute: () => AppRoute,
} as any)
const AppMonitoringRoute = AppMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AppRoute,
} as any)
const AppLaporanMonitoringRoute = AppLaporanMonitoringRouteImport.update({
  id: '/laporan-monitoring',
  path: '/laporan-monitoring',
  getParentRoute: () => AppRoute,
} as any)
const AppLaporanAwalRoute = AppLaporanAwalRouteImport.update({
  id: '/laporan-awal',
  path: '/laporan-awal',
  getParentRoute: () => AppRoute,
} as any)
const AppLaporanAkhirRoute = AppLaporanAkhirRouteImport.update({
  id: '/laporan-akhir',
  path: '/laporan-akhir',
  getParentRoute: () => AppRoute,
} as any)
const AppLapanganRoute = AppLapanganRouteImport.update({
  id: '/lapangan',
  path: '/lapangan',
  getParentRoute: () => AppRoute,
} as any)
const AppKpiRoute = AppKpiRouteImport.update({
  id: '/kpi',
  path: '/kpi',
  getParentRoute: () => AppRoute,
} as any)
const AppInspeksiMpRoute = AppInspeksiMpRouteImport.update({
  id: '/inspeksi-mp',
  path: '/inspeksi-mp',
  getParentRoute: () => AppRoute,
} as any)
const AppInspeksiGiRoute = AppInspeksiGiRouteImport.update({
  id: '/inspeksi-gi',
  path: '/inspeksi-gi',
  getParentRoute: () => AppRoute,
} as any)
const AppInspeksiGhRoute = AppInspeksiGhRouteImport.update({
  id: '/inspeksi-gh',
  path: '/inspeksi-gh',
  getParentRoute: () => AppRoute,
} as any)
const AppInspectionRoute = AppInspectionRouteImport.update({
  id: '/inspection',
  path: '/inspection',
  getParentRoute: () => AppRoute,
} as any)
const AppImportsRoute = AppImportsRouteImport.update({
  id: '/imports',
  path: '/imports',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppHarMpRoute = AppHarMpRouteImport.update({
  id: '/har-mp',
  path: '/har-mp',
  getParentRoute: () => AppRoute,
} as any)
const AppHarGiRoute = AppHarGiRouteImport.update({
  id: '/har-gi',
  path: '/har-gi',
  getParentRoute: () => AppRoute,
} as any)
const AppHarGhRoute = AppHarGhRouteImport.update({
  id: '/har-gh',
  path: '/har-gh',
  getParentRoute: () => AppRoute,
} as any)
const AppHarRoute = AppHarRouteImport.update({
  id: '/har',
  path: '/har',
  getParentRoute: () => AppRoute,
} as any)
const AppGisRoute = AppGisRouteImport.update({
  id: '/gis',
  path: '/gis',
  getParentRoute: () => AppRoute,
} as any)
const AppGiDashboardRoute = AppGiDashboardRouteImport.update({
  id: '/gi-dashboard',
  path: '/gi-dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppGarduRoute = AppGarduRouteImport.update({
  id: '/gardu',
  path: '/gardu',
  getParentRoute: () => AppRoute,
} as any)
const AppExportRoute = AppExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunicationMediaRoute = AppCommunicationMediaRouteImport.update({
  id: '/communication-media',
  path: '/communication-media',
  getParentRoute: () => AppRoute,
} as any)
const AppBayRoute = AppBayRouteImport.update({
  id: '/bay',
  path: '/bay',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetRoute = AppAssetRouteImport.update({
  id: '/asset',
  path: '/asset',
  getParentRoute: () => AppRoute,
} as any)
const AppAiSearchRoute = AppAiSearchRouteImport.update({
  id: '/ai-search',
  path: '/ai-search',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkOrderIdRoute = AppWorkOrderIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppWorkOrderRoute,
} as any)
const AppTicketsIdRoute = AppTicketsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppTicketsRoute,
} as any)
const AppPerformanceIdRoute = AppPerformanceIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPerformanceRoute,
} as any)
const AppPenyulangIdRoute = AppPenyulangIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPenyulangRoute,
} as any)
const AppLaporanCreateRoute = AppLaporanCreateRouteImport.update({
  id: '/laporan/create',
  path: '/laporan/create',
  getParentRoute: () => AppRoute,
} as any)
const AppLaporanAwalIdRoute = AppLaporanAwalIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppLaporanAwalRoute,
} as any)
const AppLaporanAkhirIdRoute = AppLaporanAkhirIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppLaporanAkhirRoute,
} as any)
const AppInspeksiMpIdRoute = AppInspeksiMpIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppInspeksiMpRoute,
} as any)
const AppInspeksiGiIdRoute = AppInspeksiGiIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppInspeksiGiRoute,
} as any)
const AppInspeksiGhIdRoute = AppInspeksiGhIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppInspeksiGhRoute,
} as any)
const AppInspectionIdRoute = AppInspectionIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppInspectionRoute,
} as any)
const AppImportsIdRoute = AppImportsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppImportsRoute,
} as any)
const AppHarIdRoute = AppHarIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppHarRoute,
} as any)
const AppHarMpIdRoute = AppHarMpIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppHarMpRoute,
} as any)
const AppHarGiIdRoute = AppHarGiIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppHarGiRoute,
} as any)
const AppHarGhIdRoute = AppHarGhIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppHarGhRoute,
} as any)
const AppGarduIdRoute = AppGarduIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppGarduRoute,
} as any)
const AppDocumentsIdRoute = AppDocumentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppDocumentsRoute,
} as any)
const AppCommunicationMediaIdRoute = AppCommunicationMediaIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCommunicationMediaRoute,
} as any)
const AppAssetIdRoute = AppAssetIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAssetRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/v2': typeof V2RouteWithChildren
  '/ai-search': typeof AppAiSearchRoute
  '/asset': typeof AppAssetRouteWithChildren
  '/bay': typeof AppBayRoute
  '/communication-media': typeof AppCommunicationMediaRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRouteWithChildren
  '/export': typeof AppExportRoute
  '/gardu': typeof AppGarduRouteWithChildren
  '/gi-dashboard': typeof AppGiDashboardRoute
  '/gis': typeof AppGisRoute
  '/har': typeof AppHarRouteWithChildren
  '/har-gh': typeof AppHarGhRouteWithChildren
  '/har-gi': typeof AppHarGiRouteWithChildren
  '/har-mp': typeof AppHarMpRouteWithChildren
  '/history': typeof AppHistoryRoute
  '/imports': typeof AppImportsRouteWithChildren
  '/inspection': typeof AppInspectionRouteWithChildren
  '/inspeksi-gh': typeof AppInspeksiGhRouteWithChildren
  '/inspeksi-gi': typeof AppInspeksiGiRouteWithChildren
  '/inspeksi-mp': typeof AppInspeksiMpRouteWithChildren
  '/kpi': typeof AppKpiRoute
  '/lapangan': typeof AppLapanganRoute
  '/laporan-akhir': typeof AppLaporanAkhirRouteWithChildren
  '/laporan-awal': typeof AppLaporanAwalRouteWithChildren
  '/laporan-monitoring': typeof AppLaporanMonitoringRoute
  '/monitoring': typeof AppMonitoringRoute
  '/penyulang': typeof AppPenyulangRouteWithChildren
  '/performance': typeof AppPerformanceRouteWithChildren
  '/personil': typeof AppPersonilRoute
  '/profile': typeof AppProfileRoute
  '/rekap': typeof AppRekapRoute
  '/rekap-akhir': typeof AppRekapAkhirRoute
  '/reports': typeof AppReportsRoute
  '/rtupp': typeof AppRtuppRoute
  '/scada': typeof AppScadaRoute
  '/scada-lines': typeof AppScadaLinesRoute
  '/scada-realtime': typeof AppScadaRealtimeRoute
  '/scada-upload': typeof AppScadaUploadRoute
  '/sync': typeof AppSyncRoute
  '/team': typeof AppTeamRoute
  '/teams': typeof AppTeamsRoute
  '/tickets': typeof AppTicketsRouteWithChildren
  '/users': typeof AppUsersRoute
  '/validasi': typeof AppValidasiRoute
  '/wall': typeof AppWallRoute
  '/work-order': typeof AppWorkOrderRouteWithChildren
  '/v2/$': typeof V2SplatRoute
  '/verify/$id': typeof VerifyIdRoute
  '/v2/': typeof V2IndexRoute
  '/asset/$id': typeof AppAssetIdRoute
  '/communication-media/$id': typeof AppCommunicationMediaIdRoute
  '/documents/$id': typeof AppDocumentsIdRoute
  '/gardu/$id': typeof AppGarduIdRoute
  '/har-gh/$id': typeof AppHarGhIdRoute
  '/har-gi/$id': typeof AppHarGiIdRoute
  '/har-mp/$id': typeof AppHarMpIdRoute
  '/har/$id': typeof AppHarIdRoute
  '/imports/$id': typeof AppImportsIdRoute
  '/inspection/$id': typeof AppInspectionIdRoute
  '/inspeksi-gh/$id': typeof AppInspeksiGhIdRoute
  '/inspeksi-gi/$id': typeof AppInspeksiGiIdRoute
  '/inspeksi-mp/$id': typeof AppInspeksiMpIdRoute
  '/laporan-akhir/$id': typeof AppLaporanAkhirIdRoute
  '/laporan-awal/$id': typeof AppLaporanAwalIdRoute
  '/laporan/create': typeof AppLaporanCreateRoute
  '/penyulang/$id': typeof AppPenyulangIdRoute
  '/performance/$id': typeof AppPerformanceIdRoute
  '/tickets/$id': typeof AppTicketsIdRoute
  '/work-order/$id': typeof AppWorkOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/ai-search': typeof AppAiSearchRoute
  '/asset': typeof AppAssetRouteWithChildren
  '/bay': typeof AppBayRoute
  '/communication-media': typeof AppCommunicationMediaRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRouteWithChildren
  '/export': typeof AppExportRoute
  '/gardu': typeof AppGarduRouteWithChildren
  '/gi-dashboard': typeof AppGiDashboardRoute
  '/gis': typeof AppGisRoute
  '/har': typeof AppHarRouteWithChildren
  '/har-gh': typeof AppHarGhRouteWithChildren
  '/har-gi': typeof AppHarGiRouteWithChildren
  '/har-mp': typeof AppHarMpRouteWithChildren
  '/history': typeof AppHistoryRoute
  '/imports': typeof AppImportsRouteWithChildren
  '/inspection': typeof AppInspectionRouteWithChildren
  '/inspeksi-gh': typeof AppInspeksiGhRouteWithChildren
  '/inspeksi-gi': typeof AppInspeksiGiRouteWithChildren
  '/inspeksi-mp': typeof AppInspeksiMpRouteWithChildren
  '/kpi': typeof AppKpiRoute
  '/lapangan': typeof AppLapanganRoute
  '/laporan-akhir': typeof AppLaporanAkhirRouteWithChildren
  '/laporan-awal': typeof AppLaporanAwalRouteWithChildren
  '/laporan-monitoring': typeof AppLaporanMonitoringRoute
  '/monitoring': typeof AppMonitoringRoute
  '/penyulang': typeof AppPenyulangRouteWithChildren
  '/performance': typeof AppPerformanceRouteWithChildren
  '/personil': typeof AppPersonilRoute
  '/profile': typeof AppProfileRoute
  '/rekap': typeof AppRekapRoute
  '/rekap-akhir': typeof AppRekapAkhirRoute
  '/reports': typeof AppReportsRoute
  '/rtupp': typeof AppRtuppRoute
  '/scada': typeof AppScadaRoute
  '/scada-lines': typeof AppScadaLinesRoute
  '/scada-realtime': typeof AppScadaRealtimeRoute
  '/scada-upload': typeof AppScadaUploadRoute
  '/sync': typeof AppSyncRoute
  '/team': typeof AppTeamRoute
  '/teams': typeof AppTeamsRoute
  '/tickets': typeof AppTicketsRouteWithChildren
  '/users': typeof AppUsersRoute
  '/validasi': typeof AppValidasiRoute
  '/wall': typeof AppWallRoute
  '/work-order': typeof AppWorkOrderRouteWithChildren
  '/v2/$': typeof V2SplatRoute
  '/verify/$id': typeof VerifyIdRoute
  '/v2': typeof V2IndexRoute
  '/asset/$id': typeof AppAssetIdRoute
  '/communication-media/$id': typeof AppCommunicationMediaIdRoute
  '/documents/$id': typeof AppDocumentsIdRoute
  '/gardu/$id': typeof AppGarduIdRoute
  '/har-gh/$id': typeof AppHarGhIdRoute
  '/har-gi/$id': typeof AppHarGiIdRoute
  '/har-mp/$id': typeof AppHarMpIdRoute
  '/har/$id': typeof AppHarIdRoute
  '/imports/$id': typeof AppImportsIdRoute
  '/inspection/$id': typeof AppInspectionIdRoute
  '/inspeksi-gh/$id': typeof AppInspeksiGhIdRoute
  '/inspeksi-gi/$id': typeof AppInspeksiGiIdRoute
  '/inspeksi-mp/$id': typeof AppInspeksiMpIdRoute
  '/laporan-akhir/$id': typeof AppLaporanAkhirIdRoute
  '/laporan-awal/$id': typeof AppLaporanAwalIdRoute
  '/laporan/create': typeof AppLaporanCreateRoute
  '/penyulang/$id': typeof AppPenyulangIdRoute
  '/performance/$id': typeof AppPerformanceIdRoute
  '/tickets/$id': typeof AppTicketsIdRoute
  '/work-order/$id': typeof AppWorkOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/_app': typeof AppRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/v2': typeof V2RouteWithChildren
  '/_app/ai-search': typeof AppAiSearchRoute
  '/_app/asset': typeof AppAssetRouteWithChildren
  '/_app/bay': typeof AppBayRoute
  '/_app/communication-media': typeof AppCommunicationMediaRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/documents': typeof AppDocumentsRouteWithChildren
  '/_app/export': typeof AppExportRoute
  '/_app/gardu': typeof AppGarduRouteWithChildren
  '/_app/gi-dashboard': typeof AppGiDashboardRoute
  '/_app/gis': typeof AppGisRoute
  '/_app/har': typeof AppHarRouteWithChildren
  '/_app/har-gh': typeof AppHarGhRouteWithChildren
  '/_app/har-gi': typeof AppHarGiRouteWithChildren
  '/_app/har-mp': typeof AppHarMpRouteWithChildren
  '/_app/history': typeof AppHistoryRoute
  '/_app/imports': typeof AppImportsRouteWithChildren
  '/_app/inspection': typeof AppInspectionRouteWithChildren
  '/_app/inspeksi-gh': typeof AppInspeksiGhRouteWithChildren
  '/_app/inspeksi-gi': typeof AppInspeksiGiRouteWithChildren
  '/_app/inspeksi-mp': typeof AppInspeksiMpRouteWithChildren
  '/_app/kpi': typeof AppKpiRoute
  '/_app/lapangan': typeof AppLapanganRoute
  '/_app/laporan-akhir': typeof AppLaporanAkhirRouteWithChildren
  '/_app/laporan-awal': typeof AppLaporanAwalRouteWithChildren
  '/_app/laporan-monitoring': typeof AppLaporanMonitoringRoute
  '/_app/monitoring': typeof AppMonitoringRoute
  '/_app/penyulang': typeof AppPenyulangRouteWithChildren
  '/_app/performance': typeof AppPerformanceRouteWithChildren
  '/_app/personil': typeof AppPersonilRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/rekap': typeof AppRekapRoute
  '/_app/rekap-akhir': typeof AppRekapAkhirRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/rtupp': typeof AppRtuppRoute
  '/_app/scada': typeof AppScadaRoute
  '/_app/scada-lines': typeof AppScadaLinesRoute
  '/_app/scada-realtime': typeof AppScadaRealtimeRoute
  '/_app/scada-upload': typeof AppScadaUploadRoute
  '/_app/sync': typeof AppSyncRoute
  '/_app/team': typeof AppTeamRoute
  '/_app/teams': typeof AppTeamsRoute
  '/_app/tickets': typeof AppTicketsRouteWithChildren
  '/_app/users': typeof AppUsersRoute
  '/_app/validasi': typeof AppValidasiRoute
  '/_app/wall': typeof AppWallRoute
  '/_app/work-order': typeof AppWorkOrderRouteWithChildren
  '/v2/$': typeof V2SplatRoute
  '/verify/$id': typeof VerifyIdRoute
  '/v2/': typeof V2IndexRoute
  '/_app/asset/$id': typeof AppAssetIdRoute
  '/_app/communication-media/$id': typeof AppCommunicationMediaIdRoute
  '/_app/documents/$id': typeof AppDocumentsIdRoute
  '/_app/gardu/$id': typeof AppGarduIdRoute
  '/_app/har-gh/$id': typeof AppHarGhIdRoute
  '/_app/har-gi/$id': typeof AppHarGiIdRoute
  '/_app/har-mp/$id': typeof AppHarMpIdRoute
  '/_app/har/$id': typeof AppHarIdRoute
  '/_app/imports/$id': typeof AppImportsIdRoute
  '/_app/inspection/$id': typeof AppInspectionIdRoute
  '/_app/inspeksi-gh/$id': typeof AppInspeksiGhIdRoute
  '/_app/inspeksi-gi/$id': typeof AppInspeksiGiIdRoute
  '/_app/inspeksi-mp/$id': typeof AppInspeksiMpIdRoute
  '/_app/laporan-akhir/$id': typeof AppLaporanAkhirIdRoute
  '/_app/laporan-awal/$id': typeof AppLaporanAwalIdRoute
  '/_app/laporan/create': typeof AppLaporanCreateRoute
  '/_app/penyulang/$id': typeof AppPenyulangIdRoute
  '/_app/performance/$id': typeof AppPerformanceIdRoute
  '/_app/tickets/$id': typeof AppTicketsIdRoute
  '/_app/work-order/$id': typeof AppWorkOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/change-password'
    | '/login'
    | '/unauthorized'
    | '/v2'
    | '/ai-search'
    | '/asset'
    | '/bay'
    | '/communication-media'
    | '/dashboard'
    | '/documents'
    | '/export'
    | '/gardu'
    | '/gi-dashboard'
    | '/gis'
    | '/har'
    | '/har-gh'
    | '/har-gi'
    | '/har-mp'
    | '/history'
    | '/imports'
    | '/inspection'
    | '/inspeksi-gh'
    | '/inspeksi-gi'
    | '/inspeksi-mp'
    | '/kpi'
    | '/lapangan'
    | '/laporan-akhir'
    | '/laporan-awal'
    | '/laporan-monitoring'
    | '/monitoring'
    | '/penyulang'
    | '/performance'
    | '/personil'
    | '/profile'
    | '/rekap'
    | '/rekap-akhir'
    | '/reports'
    | '/rtupp'
    | '/scada'
    | '/scada-lines'
    | '/scada-realtime'
    | '/scada-upload'
    | '/sync'
    | '/team'
    | '/teams'
    | '/tickets'
    | '/users'
    | '/validasi'
    | '/wall'
    | '/work-order'
    | '/v2/$'
    | '/verify/$id'
    | '/v2/'
    | '/asset/$id'
    | '/communication-media/$id'
    | '/documents/$id'
    | '/gardu/$id'
    | '/har-gh/$id'
    | '/har-gi/$id'
    | '/har-mp/$id'
    | '/har/$id'
    | '/imports/$id'
    | '/inspection/$id'
    | '/inspeksi-gh/$id'
    | '/inspeksi-gi/$id'
    | '/inspeksi-mp/$id'
    | '/laporan-akhir/$id'
    | '/laporan-awal/$id'
    | '/laporan/create'
    | '/penyulang/$id'
    | '/performance/$id'
    | '/tickets/$id'
    | '/work-order/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/change-password'
    | '/login'
    | '/unauthorized'
    | '/ai-search'
    | '/asset'
    | '/bay'
    | '/communication-media'
    | '/dashboard'
    | '/documents'
    | '/export'
    | '/gardu'
    | '/gi-dashboard'
    | '/gis'
    | '/har'
    | '/har-gh'
    | '/har-gi'
    | '/har-mp'
    | '/history'
    | '/imports'
    | '/inspection'
    | '/inspeksi-gh'
    | '/inspeksi-gi'
    | '/inspeksi-mp'
    | '/kpi'
    | '/lapangan'
    | '/laporan-akhir'
    | '/laporan-awal'
    | '/laporan-monitoring'
    | '/monitoring'
    | '/penyulang'
    | '/performance'
    | '/personil'
    | '/profile'
    | '/rekap'
    | '/rekap-akhir'
    | '/reports'
    | '/rtupp'
    | '/scada'
    | '/scada-lines'
    | '/scada-realtime'
    | '/scada-upload'
    | '/sync'
    | '/team'
    | '/teams'
    | '/tickets'
    | '/users'
    | '/validasi'
    | '/wall'
    | '/work-order'
    | '/v2/$'
    | '/verify/$id'
    | '/v2'
    | '/asset/$id'
    | '/communication-media/$id'
    | '/documents/$id'
    | '/gardu/$id'
    | '/har-gh/$id'
    | '/har-gi/$id'
    | '/har-mp/$id'
    | '/har/$id'
    | '/imports/$id'
    | '/inspection/$id'
    | '/inspeksi-gh/$id'
    | '/inspeksi-gi/$id'
    | '/inspeksi-mp/$id'
    | '/laporan-akhir/$id'
    | '/laporan-awal/$id'
    | '/laporan/create'
    | '/penyulang/$id'
    | '/performance/$id'
    | '/tickets/$id'
    | '/work-order/$id'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/_app'
    | '/change-password'
    | '/login'
    | '/unauthorized'
    | '/v2'
    | '/_app/ai-search'
    | '/_app/asset'
    | '/_app/bay'
    | '/_app/communication-media'
    | '/_app/dashboard'
    | '/_app/documents'
    | '/_app/export'
    | '/_app/gardu'
    | '/_app/gi-dashboard'
    | '/_app/gis'
    | '/_app/har'
    | '/_app/har-gh'
    | '/_app/har-gi'
    | '/_app/har-mp'
    | '/_app/history'
    | '/_app/imports'
    | '/_app/inspection'
    | '/_app/inspeksi-gh'
    | '/_app/inspeksi-gi'
    | '/_app/inspeksi-mp'
    | '/_app/kpi'
    | '/_app/lapangan'
    | '/_app/laporan-akhir'
    | '/_app/laporan-awal'
    | '/_app/laporan-monitoring'
    | '/_app/monitoring'
    | '/_app/penyulang'
    | '/_app/performance'
    | '/_app/personil'
    | '/_app/profile'
    | '/_app/rekap'
    | '/_app/rekap-akhir'
    | '/_app/reports'
    | '/_app/rtupp'
    | '/_app/scada'
    | '/_app/scada-lines'
    | '/_app/scada-realtime'
    | '/_app/scada-upload'
    | '/_app/sync'
    | '/_app/team'
    | '/_app/teams'
    | '/_app/tickets'
    | '/_app/users'
    | '/_app/validasi'
    | '/_app/wall'
    | '/_app/work-order'
    | '/v2/$'
    | '/verify/$id'
    | '/v2/'
    | '/_app/asset/$id'
    | '/_app/communication-media/$id'
    | '/_app/documents/$id'
    | '/_app/gardu/$id'
    | '/_app/har-gh/$id'
    | '/_app/har-gi/$id'
    | '/_app/har-mp/$id'
    | '/_app/har/$id'
    | '/_app/imports/$id'
    | '/_app/inspection/$id'
    | '/_app/inspeksi-gh/$id'
    | '/_app/inspeksi-gi/$id'
    | '/_app/inspeksi-mp/$id'
    | '/_app/laporan-akhir/$id'
    | '/_app/laporan-awal/$id'
    | '/_app/laporan/create'
    | '/_app/penyulang/$id'
    | '/_app/performance/$id'
    | '/_app/tickets/$id'
    | '/_app/work-order/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  AppRoute: typeof AppRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  LoginRoute: typeof LoginRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  V2Route: typeof V2RouteWithChildren
  VerifyIdRoute: typeof VerifyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/v2': {
      id: '/v2'
      path: '/v2'
      fullPath: '/v2'
      preLoaderRoute: typeof V2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v2/': {
      id: '/v2/'
      path: '/'
      fullPath: '/v2/'
      preLoaderRoute: typeof V2IndexRouteImport
      parentRoute: typeof V2Route
    }
    '/verify/$id': {
      id: '/verify/$id'
      path: '/verify/$id'
      fullPath: '/verify/$id'
      preLoaderRoute: typeof VerifyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v2/$': {
      id: '/v2/$'
      path: '/$'
      fullPath: '/v2/$'
      preLoaderRoute: typeof V2SplatRouteImport
      parentRoute: typeof V2Route
    }
    '/_app/work-order': {
      id: '/_app/work-order'
      path: '/work-order'
      fullPath: '/work-order'
      preLoaderRoute: typeof AppWorkOrderRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wall': {
      id: '/_app/wall'
      path: '/wall'
      fullPath: '/wall'
      preLoaderRoute: typeof AppWallRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/validasi': {
      id: '/_app/validasi'
      path: '/validasi'
      fullPath: '/validasi'
      preLoaderRoute: typeof AppValidasiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tickets': {
      id: '/_app/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AppTicketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teams': {
      id: '/_app/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AppTeamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sync': {
      id: '/_app/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof AppSyncRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scada-upload': {
      id: '/_app/scada-upload'
      path: '/scada-upload'
      fullPath: '/scada-upload'
      preLoaderRoute: typeof AppScadaUploadRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scada-realtime': {
      id: '/_app/scada-realtime'
      path: '/scada-realtime'
      fullPath: '/scada-realtime'
      preLoaderRoute: typeof AppScadaRealtimeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scada-lines': {
      id: '/_app/scada-lines'
      path: '/scada-lines'
      fullPath: '/scada-lines'
      preLoaderRoute: typeof AppScadaLinesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scada': {
      id: '/_app/scada'
      path: '/scada'
      fullPath: '/scada'
      preLoaderRoute: typeof AppScadaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rtupp': {
      id: '/_app/rtupp'
      path: '/rtupp'
      fullPath: '/rtupp'
      preLoaderRoute: typeof AppRtuppRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rekap-akhir': {
      id: '/_app/rekap-akhir'
      path: '/rekap-akhir'
      fullPath: '/rekap-akhir'
      preLoaderRoute: typeof AppRekapAkhirRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rekap': {
      id: '/_app/rekap'
      path: '/rekap'
      fullPath: '/rekap'
      preLoaderRoute: typeof AppRekapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/personil': {
      id: '/_app/personil'
      path: '/personil'
      fullPath: '/personil'
      preLoaderRoute: typeof AppPersonilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/performance': {
      id: '/_app/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AppPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/penyulang': {
      id: '/_app/penyulang'
      path: '/penyulang'
      fullPath: '/penyulang'
      preLoaderRoute: typeof AppPenyulangRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/monitoring': {
      id: '/_app/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof AppMonitoringRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/laporan-monitoring': {
      id: '/_app/laporan-monitoring'
      path: '/laporan-monitoring'
      fullPath: '/laporan-monitoring'
      preLoaderRoute: typeof AppLaporanMonitoringRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/laporan-awal': {
      id: '/_app/laporan-awal'
      path: '/laporan-awal'
      fullPath: '/laporan-awal'
      preLoaderRoute: typeof AppLaporanAwalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/laporan-akhir': {
      id: '/_app/laporan-akhir'
      path: '/laporan-akhir'
      fullPath: '/laporan-akhir'
      preLoaderRoute: typeof AppLaporanAkhirRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lapangan': {
      id: '/_app/lapangan'
      path: '/lapangan'
      fullPath: '/lapangan'
      preLoaderRoute: typeof AppLapanganRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kpi': {
      id: '/_app/kpi'
      path: '/kpi'
      fullPath: '/kpi'
      preLoaderRoute: typeof AppKpiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inspeksi-mp': {
      id: '/_app/inspeksi-mp'
      path: '/inspeksi-mp'
      fullPath: '/inspeksi-mp'
      preLoaderRoute: typeof AppInspeksiMpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inspeksi-gi': {
      id: '/_app/inspeksi-gi'
      path: '/inspeksi-gi'
      fullPath: '/inspeksi-gi'
      preLoaderRoute: typeof AppInspeksiGiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inspeksi-gh': {
      id: '/_app/inspeksi-gh'
      path: '/inspeksi-gh'
      fullPath: '/inspeksi-gh'
      preLoaderRoute: typeof AppInspeksiGhRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inspection': {
      id: '/_app/inspection'
      path: '/inspection'
      fullPath: '/inspection'
      preLoaderRoute: typeof AppInspectionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/imports': {
      id: '/_app/imports'
      path: '/imports'
      fullPath: '/imports'
      preLoaderRoute: typeof AppImportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/har-mp': {
      id: '/_app/har-mp'
      path: '/har-mp'
      fullPath: '/har-mp'
      preLoaderRoute: typeof AppHarMpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/har-gi': {
      id: '/_app/har-gi'
      path: '/har-gi'
      fullPath: '/har-gi'
      preLoaderRoute: typeof AppHarGiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/har-gh': {
      id: '/_app/har-gh'
      path: '/har-gh'
      fullPath: '/har-gh'
      preLoaderRoute: typeof AppHarGhRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/har': {
      id: '/_app/har'
      path: '/har'
      fullPath: '/har'
      preLoaderRoute: typeof AppHarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gis': {
      id: '/_app/gis'
      path: '/gis'
      fullPath: '/gis'
      preLoaderRoute: typeof AppGisRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gi-dashboard': {
      id: '/_app/gi-dashboard'
      path: '/gi-dashboard'
      fullPath: '/gi-dashboard'
      preLoaderRoute: typeof AppGiDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gardu': {
      id: '/_app/gardu'
      path: '/gardu'
      fullPath: '/gardu'
      preLoaderRoute: typeof AppGarduRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/export': {
      id: '/_app/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof AppExportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/communication-media': {
      id: '/_app/communication-media'
      path: '/communication-media'
      fullPath: '/communication-media'
      preLoaderRoute: typeof AppCommunicationMediaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bay': {
      id: '/_app/bay'
      path: '/bay'
      fullPath: '/bay'
      preLoaderRoute: typeof AppBayRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/asset': {
      id: '/_app/asset'
      path: '/asset'
      fullPath: '/asset'
      preLoaderRoute: typeof AppAssetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-search': {
      id: '/_app/ai-search'
      path: '/ai-search'
      fullPath: '/ai-search'
      preLoaderRoute: typeof AppAiSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/work-order/$id': {
      id: '/_app/work-order/$id'
      path: '/$id'
      fullPath: '/work-order/$id'
      preLoaderRoute: typeof AppWorkOrderIdRouteImport
      parentRoute: typeof AppWorkOrderRoute
    }
    '/_app/tickets/$id': {
      id: '/_app/tickets/$id'
      path: '/$id'
      fullPath: '/tickets/$id'
      preLoaderRoute: typeof AppTicketsIdRouteImport
      parentRoute: typeof AppTicketsRoute
    }
    '/_app/performance/$id': {
      id: '/_app/performance/$id'
      path: '/$id'
      fullPath: '/performance/$id'
      preLoaderRoute: typeof AppPerformanceIdRouteImport
      parentRoute: typeof AppPerformanceRoute
    }
    '/_app/penyulang/$id': {
      id: '/_app/penyulang/$id'
      path: '/$id'
      fullPath: '/penyulang/$id'
      preLoaderRoute: typeof AppPenyulangIdRouteImport
      parentRoute: typeof AppPenyulangRoute
    }
    '/_app/laporan/create': {
      id: '/_app/laporan/create'
      path: '/laporan/create'
      fullPath: '/laporan/create'
      preLoaderRoute: typeof AppLaporanCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/laporan-awal/$id': {
      id: '/_app/laporan-awal/$id'
      path: '/$id'
      fullPath: '/laporan-awal/$id'
      preLoaderRoute: typeof AppLaporanAwalIdRouteImport
      parentRoute: typeof AppLaporanAwalRoute
    }
    '/_app/laporan-akhir/$id': {
      id: '/_app/laporan-akhir/$id'
      path: '/$id'
      fullPath: '/laporan-akhir/$id'
      preLoaderRoute: typeof AppLaporanAkhirIdRouteImport
      parentRoute: typeof AppLaporanAkhirRoute
    }
    '/_app/inspeksi-mp/$id': {
      id: '/_app/inspeksi-mp/$id'
      path: '/$id'
      fullPath: '/inspeksi-mp/$id'
      preLoaderRoute: typeof AppInspeksiMpIdRouteImport
      parentRoute: typeof AppInspeksiMpRoute
    }
    '/_app/inspeksi-gi/$id': {
      id: '/_app/inspeksi-gi/$id'
      path: '/$id'
      fullPath: '/inspeksi-gi/$id'
      preLoaderRoute: typeof AppInspeksiGiIdRouteImport
      parentRoute: typeof AppInspeksiGiRoute
    }
    '/_app/inspeksi-gh/$id': {
      id: '/_app/inspeksi-gh/$id'
      path: '/$id'
      fullPath: '/inspeksi-gh/$id'
      preLoaderRoute: typeof AppInspeksiGhIdRouteImport
      parentRoute: typeof AppInspeksiGhRoute
    }
    '/_app/inspection/$id': {
      id: '/_app/inspection/$id'
      path: '/$id'
      fullPath: '/inspection/$id'
      preLoaderRoute: typeof AppInspectionIdRouteImport
      parentRoute: typeof AppInspectionRoute
    }
    '/_app/imports/$id': {
      id: '/_app/imports/$id'
      path: '/$id'
      fullPath: '/imports/$id'
      preLoaderRoute: typeof AppImportsIdRouteImport
      parentRoute: typeof AppImportsRoute
    }
    '/_app/har/$id': {
      id: '/_app/har/$id'
      path: '/$id'
      fullPath: '/har/$id'
      preLoaderRoute: typeof AppHarIdRouteImport
      parentRoute: typeof AppHarRoute
    }
    '/_app/har-mp/$id': {
      id: '/_app/har-mp/$id'
      path: '/$id'
      fullPath: '/har-mp/$id'
      preLoaderRoute: typeof AppHarMpIdRouteImport
      parentRoute: typeof AppHarMpRoute
    }
    '/_app/har-gi/$id': {
      id: '/_app/har-gi/$id'
      path: '/$id'
      fullPath: '/har-gi/$id'
      preLoaderRoute: typeof AppHarGiIdRouteImport
      parentRoute: typeof AppHarGiRoute
    }
    '/_app/har-gh/$id': {
      id: '/_app/har-gh/$id'
      path: '/$id'
      fullPath: '/har-gh/$id'
      preLoaderRoute: typeof AppHarGhIdRouteImport
      parentRoute: typeof AppHarGhRoute
    }
    '/_app/gardu/$id': {
      id: '/_app/gardu/$id'
      path: '/$id'
      fullPath: '/gardu/$id'
      preLoaderRoute: typeof AppGarduIdRouteImport
      parentRoute: typeof AppGarduRoute
    }
    '/_app/documents/$id': {
      id: '/_app/documents/$id'
      path: '/$id'
      fullPath: '/documents/$id'
      preLoaderRoute: typeof AppDocumentsIdRouteImport
      parentRoute: typeof AppDocumentsRoute
    }
    '/_app/communication-media/$id': {
      id: '/_app/communication-media/$id'
      path: '/$id'
      fullPath: '/communication-media/$id'
      preLoaderRoute: typeof AppCommunicationMediaIdRouteImport
      parentRoute: typeof AppCommunicationMediaRoute
    }
    '/_app/asset/$id': {
      id: '/_app/asset/$id'
      path: '/$id'
      fullPath: '/asset/$id'
      preLoaderRoute: typeof AppAssetIdRouteImport
      parentRoute: typeof AppAssetRoute
    }
  }
}

interface AppAssetRouteChildren {
  AppAssetIdRoute: typeof AppAssetIdRoute
}

const AppAssetRouteChildren: AppAssetRouteChildren = {
  AppAssetIdRoute: AppAssetIdRoute,
}

const AppAssetRouteWithChildren = AppAssetRoute._addFileChildren(
  AppAssetRouteChildren,
)

interface AppCommunicationMediaRouteChildren {
  AppCommunicationMediaIdRoute: typeof AppCommunicationMediaIdRoute
}

const AppCommunicationMediaRouteChildren: AppCommunicationMediaRouteChildren = {
  AppCommunicationMediaIdRoute: AppCommunicationMediaIdRoute,
}

const AppCommunicationMediaRouteWithChildren =
  AppCommunicationMediaRoute._addFileChildren(
    AppCommunicationMediaRouteChildren,
  )

interface AppDocumentsRouteChildren {
  AppDocumentsIdRoute: typeof AppDocumentsIdRoute
}

const AppDocumentsRouteChildren: AppDocumentsRouteChildren = {
  AppDocumentsIdRoute: AppDocumentsIdRoute,
}

const AppDocumentsRouteWithChildren = AppDocumentsRoute._addFileChildren(
  AppDocumentsRouteChildren,
)

interface AppGarduRouteChildren {
  AppGarduIdRoute: typeof AppGarduIdRoute
}

const AppGarduRouteChildren: AppGarduRouteChildren = {
  AppGarduIdRoute: AppGarduIdRoute,
}

const AppGarduRouteWithChildren = AppGarduRoute._addFileChildren(
  AppGarduRouteChildren,
)

interface AppHarRouteChildren {
  AppHarIdRoute: typeof AppHarIdRoute
}

const AppHarRouteChildren: AppHarRouteChildren = {
  AppHarIdRoute: AppHarIdRoute,
}

const AppHarRouteWithChildren =
  AppHarRoute._addFileChildren(AppHarRouteChildren)

interface AppHarGhRouteChildren {
  AppHarGhIdRoute: typeof AppHarGhIdRoute
}

const AppHarGhRouteChildren: AppHarGhRouteChildren = {
  AppHarGhIdRoute: AppHarGhIdRoute,
}

const AppHarGhRouteWithChildren = AppHarGhRoute._addFileChildren(
  AppHarGhRouteChildren,
)

interface AppHarGiRouteChildren {
  AppHarGiIdRoute: typeof AppHarGiIdRoute
}

const AppHarGiRouteChildren: AppHarGiRouteChildren = {
  AppHarGiIdRoute: AppHarGiIdRoute,
}

const AppHarGiRouteWithChildren = AppHarGiRoute._addFileChildren(
  AppHarGiRouteChildren,
)

interface AppHarMpRouteChildren {
  AppHarMpIdRoute: typeof AppHarMpIdRoute
}

const AppHarMpRouteChildren: AppHarMpRouteChildren = {
  AppHarMpIdRoute: AppHarMpIdRoute,
}

const AppHarMpRouteWithChildren = AppHarMpRoute._addFileChildren(
  AppHarMpRouteChildren,
)

interface AppImportsRouteChildren {
  AppImportsIdRoute: typeof AppImportsIdRoute
}

const AppImportsRouteChildren: AppImportsRouteChildren = {
  AppImportsIdRoute: AppImportsIdRoute,
}

const AppImportsRouteWithChildren = AppImportsRoute._addFileChildren(
  AppImportsRouteChildren,
)

interface AppInspectionRouteChildren {
  AppInspectionIdRoute: typeof AppInspectionIdRoute
}

const AppInspectionRouteChildren: AppInspectionRouteChildren = {
  AppInspectionIdRoute: AppInspectionIdRoute,
}

const AppInspectionRouteWithChildren = AppInspectionRoute._addFileChildren(
  AppInspectionRouteChildren,
)

interface AppInspeksiGhRouteChildren {
  AppInspeksiGhIdRoute: typeof AppInspeksiGhIdRoute
}

const AppInspeksiGhRouteChildren: AppInspeksiGhRouteChildren = {
  AppInspeksiGhIdRoute: AppInspeksiGhIdRoute,
}

const AppInspeksiGhRouteWithChildren = AppInspeksiGhRoute._addFileChildren(
  AppInspeksiGhRouteChildren,
)

interface AppInspeksiGiRouteChildren {
  AppInspeksiGiIdRoute: typeof AppInspeksiGiIdRoute
}

const AppInspeksiGiRouteChildren: AppInspeksiGiRouteChildren = {
  AppInspeksiGiIdRoute: AppInspeksiGiIdRoute,
}

const AppInspeksiGiRouteWithChildren = AppInspeksiGiRoute._addFileChildren(
  AppInspeksiGiRouteChildren,
)

interface AppInspeksiMpRouteChildren {
  AppInspeksiMpIdRoute: typeof AppInspeksiMpIdRoute
}

const AppInspeksiMpRouteChildren: AppInspeksiMpRouteChildren = {
  AppInspeksiMpIdRoute: AppInspeksiMpIdRoute,
}

const AppInspeksiMpRouteWithChildren = AppInspeksiMpRoute._addFileChildren(
  AppInspeksiMpRouteChildren,
)

interface AppLaporanAkhirRouteChildren {
  AppLaporanAkhirIdRoute: typeof AppLaporanAkhirIdRoute
}

const AppLaporanAkhirRouteChildren: AppLaporanAkhirRouteChildren = {
  AppLaporanAkhirIdRoute: AppLaporanAkhirIdRoute,
}

const AppLaporanAkhirRouteWithChildren = AppLaporanAkhirRoute._addFileChildren(
  AppLaporanAkhirRouteChildren,
)

interface AppLaporanAwalRouteChildren {
  AppLaporanAwalIdRoute: typeof AppLaporanAwalIdRoute
}

const AppLaporanAwalRouteChildren: AppLaporanAwalRouteChildren = {
  AppLaporanAwalIdRoute: AppLaporanAwalIdRoute,
}

const AppLaporanAwalRouteWithChildren = AppLaporanAwalRoute._addFileChildren(
  AppLaporanAwalRouteChildren,
)

interface AppPenyulangRouteChildren {
  AppPenyulangIdRoute: typeof AppPenyulangIdRoute
}

const AppPenyulangRouteChildren: AppPenyulangRouteChildren = {
  AppPenyulangIdRoute: AppPenyulangIdRoute,
}

const AppPenyulangRouteWithChildren = AppPenyulangRoute._addFileChildren(
  AppPenyulangRouteChildren,
)

interface AppPerformanceRouteChildren {
  AppPerformanceIdRoute: typeof AppPerformanceIdRoute
}

const AppPerformanceRouteChildren: AppPerformanceRouteChildren = {
  AppPerformanceIdRoute: AppPerformanceIdRoute,
}

const AppPerformanceRouteWithChildren = AppPerformanceRoute._addFileChildren(
  AppPerformanceRouteChildren,
)

interface AppTicketsRouteChildren {
  AppTicketsIdRoute: typeof AppTicketsIdRoute
}

const AppTicketsRouteChildren: AppTicketsRouteChildren = {
  AppTicketsIdRoute: AppTicketsIdRoute,
}

const AppTicketsRouteWithChildren = AppTicketsRoute._addFileChildren(
  AppTicketsRouteChildren,
)

interface AppWorkOrderRouteChildren {
  AppWorkOrderIdRoute: typeof AppWorkOrderIdRoute
}

const AppWorkOrderRouteChildren: AppWorkOrderRouteChildren = {
  AppWorkOrderIdRoute: AppWorkOrderIdRoute,
}

const AppWorkOrderRouteWithChildren = AppWorkOrderRoute._addFileChildren(
  AppWorkOrderRouteChildren,
)

interface AppRouteChildren {
  AppAiSearchRoute: typeof AppAiSearchRoute
  AppAssetRoute: typeof AppAssetRouteWithChildren
  AppBayRoute: typeof AppBayRoute
  AppCommunicationMediaRoute: typeof AppCommunicationMediaRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppDocumentsRoute: typeof AppDocumentsRouteWithChildren
  AppExportRoute: typeof AppExportRoute
  AppGarduRoute: typeof AppGarduRouteWithChildren
  AppGiDashboardRoute: typeof AppGiDashboardRoute
  AppGisRoute: typeof AppGisRoute
  AppHarRoute: typeof AppHarRouteWithChildren
  AppHarGhRoute: typeof AppHarGhRouteWithChildren
  AppHarGiRoute: typeof AppHarGiRouteWithChildren
  AppHarMpRoute: typeof AppHarMpRouteWithChildren
  AppHistoryRoute: typeof AppHistoryRoute
  AppImportsRoute: typeof AppImportsRouteWithChildren
  AppInspectionRoute: typeof AppInspectionRouteWithChildren
  AppInspeksiGhRoute: typeof AppInspeksiGhRouteWithChildren
  AppInspeksiGiRoute: typeof AppInspeksiGiRouteWithChildren
  AppInspeksiMpRoute: typeof AppInspeksiMpRouteWithChildren
  AppKpiRoute: typeof AppKpiRoute
  AppLapanganRoute: typeof AppLapanganRoute
  AppLaporanAkhirRoute: typeof AppLaporanAkhirRouteWithChildren
  AppLaporanAwalRoute: typeof AppLaporanAwalRouteWithChildren
  AppLaporanMonitoringRoute: typeof AppLaporanMonitoringRoute
  AppMonitoringRoute: typeof AppMonitoringRoute
  AppPenyulangRoute: typeof AppPenyulangRouteWithChildren
  AppPerformanceRoute: typeof AppPerformanceRouteWithChildren
  AppPersonilRoute: typeof AppPersonilRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRekapRoute: typeof AppRekapRoute
  AppRekapAkhirRoute: typeof AppRekapAkhirRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRtuppRoute: typeof AppRtuppRoute
  AppScadaRoute: typeof AppScadaRoute
  AppScadaLinesRoute: typeof AppScadaLinesRoute
  AppScadaRealtimeRoute: typeof AppScadaRealtimeRoute
  AppScadaUploadRoute: typeof AppScadaUploadRoute
  AppSyncRoute: typeof AppSyncRoute
  AppTeamRoute: typeof AppTeamRoute
  AppTeamsRoute: typeof AppTeamsRoute
  AppTicketsRoute: typeof AppTicketsRouteWithChildren
  AppUsersRoute: typeof AppUsersRoute
  AppValidasiRoute: typeof AppValidasiRoute
  AppWallRoute: typeof AppWallRoute
  AppWorkOrderRoute: typeof AppWorkOrderRouteWithChildren
  AppLaporanCreateRoute: typeof AppLaporanCreateRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiSearchRoute: AppAiSearchRoute,
  AppAssetRoute: AppAssetRouteWithChildren,
  AppBayRoute: AppBayRoute,
  AppCommunicationMediaRoute: AppCommunicationMediaRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppDocumentsRoute: AppDocumentsRouteWithChildren,
  AppExportRoute: AppExportRoute,
  AppGarduRoute: AppGarduRouteWithChildren,
  AppGiDashboardRoute: AppGiDashboardRoute,
  AppGisRoute: AppGisRoute,
  AppHarRoute: AppHarRouteWithChildren,
  AppHarGhRoute: AppHarGhRouteWithChildren,
  AppHarGiRoute: AppHarGiRouteWithChildren,
  AppHarMpRoute: AppHarMpRouteWithChildren,
  AppHistoryRoute: AppHistoryRoute,
  AppImportsRoute: AppImportsRouteWithChildren,
  AppInspectionRoute: AppInspectionRouteWithChildren,
  AppInspeksiGhRoute: AppInspeksiGhRouteWithChildren,
  AppInspeksiGiRoute: AppInspeksiGiRouteWithChildren,
  AppInspeksiMpRoute: AppInspeksiMpRouteWithChildren,
  AppKpiRoute: AppKpiRoute,
  AppLapanganRoute: AppLapanganRoute,
  AppLaporanAkhirRoute: AppLaporanAkhirRouteWithChildren,
  AppLaporanAwalRoute: AppLaporanAwalRouteWithChildren,
  AppLaporanMonitoringRoute: AppLaporanMonitoringRoute,
  AppMonitoringRoute: AppMonitoringRoute,
  AppPenyulangRoute: AppPenyulangRouteWithChildren,
  AppPerformanceRoute: AppPerformanceRouteWithChildren,
  AppPersonilRoute: AppPersonilRoute,
  AppProfileRoute: AppProfileRoute,
  AppRekapRoute: AppRekapRoute,
  AppRekapAkhirRoute: AppRekapAkhirRoute,
  AppReportsRoute: AppReportsRoute,
  AppRtuppRoute: AppRtuppRoute,
  AppScadaRoute: AppScadaRoute,
  AppScadaLinesRoute: AppScadaLinesRoute,
  AppScadaRealtimeRoute: AppScadaRealtimeRoute,
  AppScadaUploadRoute: AppScadaUploadRoute,
  AppSyncRoute: AppSyncRoute,
  AppTeamRoute: AppTeamRoute,
  AppTeamsRoute: AppTeamsRoute,
  AppTicketsRoute: AppTicketsRouteWithChildren,
  AppUsersRoute: AppUsersRoute,
  AppValidasiRoute: AppValidasiRoute,
  AppWallRoute: AppWallRoute,
  AppWorkOrderRoute: AppWorkOrderRouteWithChildren,
  AppLaporanCreateRoute: AppLaporanCreateRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface V2RouteChildren {
  V2SplatRoute: typeof V2SplatRoute
  V2IndexRoute: typeof V2IndexRoute
}

const V2RouteChildren: V2RouteChildren = {
  V2SplatRoute: V2SplatRoute,
  V2IndexRoute: V2IndexRoute,
}

const V2RouteWithChildren = V2Route._addFileChildren(V2RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  AppRoute: AppRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  LoginRoute: LoginRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  V2Route: V2RouteWithChildren,
  VerifyIdRoute: VerifyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
